version: '3.8'
services:
  postgresqldb:
    image: postgres
    environment:
      POSTGRES_DB: complaintDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8001:5432"
    networks:
      - same-net
  spring-app:
    build: .
    image: complaint
    container_name: spring-app
    depends_on:
      - postgresqldb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresqldb:5432/complaintDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - same-net

networks:
  same-net:
    driver: bridge